### ISSUE TITLE
top navigation bar problem on mobile

### ISSUE THREAD

**Issue by NatTheBag** [Pixelators4014/Pixelators4014.github.io#29]
line skip makes the top navigation bar look weird. functional but now its like 3 lines for every button. maybe change it so that it wraps around (like fit as many on one row then go to the next one)? just go on the website in mobile you'll see the issue.

**Comment by arihant2math** [comment]
Reproducible

**Comment by arihant2math** [comment]
Redo the mobile navbar with a breakpoint @AlistairKeiller (I'm not that experienced with tailwind)

**Comment by AlistairKeiller** [comment]
yep, sg, will do tmmrw

**Comment by arihant2math** [comment]
alr I'm doing this ...

**Comment by arihant2math** [comment]
fixing with #38
